def fibSeq(n):
    fib = []
    if n == 0:
        fib = [0]
    if n == 1:
        fib = [0, 1]
    i = 2
    fib =[0, 1]
    while i < n:
        fib.append(fib[i - 1] + fib[i - 2])
        i += 1
    return fib

print("Fib sequences generated by while loop :")
print(n for n in fibSeq(10))
